/* @(#)Z 1.4 os2/src/core/idl/Settings.idl, odcore, od96os2, odos29646d 96/11/15 15:53:53 (96/08/23 01:40:58) */
//#====START_GENERATED_PROLOG======================================
//#
//#
//#   COMPONENT_NAME: odcore
//#
//#   CLASSES: none
//#
//#   ORIGINS: 82,27
//#
//#
//#   (C) COPYRIGHT International Business Machines Corp. 1995,1996
//#   All Rights Reserved
//#   Licensed Materials - Property of IBM
//#   US Government Users Restricted Rights - Use, duplication or
//#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//#   	
//#   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
//#   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//#   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
//#   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
//#   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
//#   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
//#   OR PERFORMANCE OF THIS SOFTWARE.
//#
//#====END_GENERATED_PROLOG========================================
//#

#ifdef __PRIVATE__
//#
//#     File:           Settings.idl
//#
//#     Contains:       Class definition for ODSettingsExtension
//#
//#     Owned by:       Tantek eelik
//#
//#     Copyright:      (r) 1994 - 1995 by Apple Computer, Inc., all rights reserved.
//#
//#
//#     To Do:
//#
#else
//#     Copyright:      (r) 1994 by Apple Computer, Inc., all rights reserved.
#endif

#ifndef _SETTINGS_
#define _SETTINGS_

#ifndef _EXTENSN_
#include "Extensn.idl"
#endif

//==============================================================================
// Classes defined in this interface
//==============================================================================

interface   ODSettingsExtension;

//==============================================================================
// Classes used by this interface
//==============================================================================

interface   ODFacet;
interface   ODPart;

//=====================================================================================
// Implementation Types
//=====================================================================================

typedef somToken HMODULE;
typedef somToken PFNWP;
typedef  somToken HPROPSHEETPAGE;


#ifdef __PRIVATE__
#if defined(__SOMIDL__)
#pragma somemittypes on
#endif

// Array of sheet resources needed to load additional settings pages
struct ODSheet
{
  PFNWP    dlgproc;       // dialog procedure
  HMODULE  hmod;          //  resource module
  ULONG    id;            //  dialog template id
};

#if defined(__SOMIDL__)
#pragma somemittypes off
#endif
#endif //# __PRIVATE__


//==============================================================================
// ODSettingsExtension
//==============================================================================

interface ODSettingsExtension : ODExtension
{
        void InitSettingsExtension(in ODPart owner,
                                   in ODULong page_count,
                                   in ODFacet facet);

        void ShowSettings(in ODFacet facet);

        // set array of part's property sheet resources
        void  AddNotebookSheet(in PFNWP  dlgproc, in HMODULE hMod, in ULONG dlg_id);


#ifdef __PRIVATE__

        // get array of part's property sheet resources & sheet count
        void  GetNotebookSheets(out  ODSheet* Sheet, out ODULong sheet_count);

#endif //# __PRIVATE__


#ifdef __SOMIDL__
        implementation
        {
                functionprefix = ODSettingsExtension;

                override:
                        somUninit,
                        Release;
                releaseorder:
                        InitSettingsExtension,
                        ShowSettings,
                        AddNotebookSheet,
                        GetNotebookSheets;


          passthru C_xh =
                ""
                "#include <os2.h> "
                "";



          #ifdef __PRIVATE__

               ODULong fsheet_count;
               ODSheet fSheet[10];

               // number of setting pages to be inserted into the property
               // notebook, set by call to InitSettngsExtension
               ODULong fnumpagesneeded;


          #endif //# __PRIVATE__

        };
#endif
};


#endif //# _SETTINGS_
