/* @(#)Z 1.3 com/src/registry/ODPrtReg.cpp, odconfig, od96os2, odos29646d 96/11/15 15:49:15 (96/10/29 09:29:05) */
//====START_GENERATED_PROLOG======================================
//
//
//   COMPONENT_NAME: odconfig
//
//   CLASSES: none
//
//   ORIGINS: 27
//
//
//   (C) COPYRIGHT International Business Machines Corp. 1995,1996
//   All Rights Reserved
//   Licensed Materials - Property of IBM
//   US Government Users Restricted Rights - Use, duplication or
//   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//   	
//   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
//   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
//   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
//   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
//   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
//   OR PERFORMANCE OF THIS SOFTWARE.
//
//====END_GENERATED_PROLOG========================================
//

/********************************************************************/
/*  Licensed Materials - Property of IBM                            */
/*                                                                  */
/*                                                                  */
/* Copyright (C) International Business Machines Corp., 1994.       */
/* Copyright (C) Apple Computer, Inc., 1994                         */
/*                                                                  */
/*  US Government Users Restricted Rights -                         */
/*  Use, duplication, or disclosure restricted                      */
/*  by GSA ADP Schedule Contract with IBM Corp.                     */
/*                                                                  */
/*  IBM Change History (most recent first):                         */
/*  128523   09/28/95   jso  Added File Category preferences        */
/*  123473   07/14/95   jso  Added FileType/Ext preferences         */
/*  123479   06/28/95   jso  Added UpdateODPartHandlerInfo          */
/********************************************************************/
/*
 *  This file was generated by the SOM Compiler.
 *  Generated using:
 *     SOM incremental update: somc/smmain.c
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using:
 *      SOM Emitter emitxtm: somc/smmain.c
 */

#define ODPartHandlerRegistry_Class_Source

#include <ODTypes.h>

#include <ODPrtReg.xih>

#ifdef _PLATFORM_OS2_
#include <ODPagtun.h>
#endif

SOM_Scope long  SOMLINK ODPartHandlerRegistryRegisterPartHandlerClass(ODPartHandlerRegistry *somSelf,
                                                                       Environment *ev,
                                                                      string className,
                                                                      string DLLName,
                                                                      long cTemplate,  
                                                                      long reserved)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryRegisterPartHandlerClass");

    /* Return statement to be customized: */
    { long retVal;  return (retVal); }
}

SOM_Scope long  SOMLINK ODPartHandlerRegistryDeregisterPartHandler(ODPartHandlerRegistry *somSelf,
                                                                    Environment *ev,
                                                                   ISOString partHandlerName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryDeregisterPartHandler");

    /* Return statement to be customized: */
    { long retVal;  return (retVal); }
}

SOM_Scope long  SOMLINK ODPartHandlerRegistryDeregisterPartHandlerClass(ODPartHandlerRegistry *somSelf,
                                                                         Environment *ev,
                                                                        string partHandlerName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryDeregisterPartHandlerClass");

    /* Return statement to be customized: */
    { long retVal;  return (retVal); }
}

SOM_Scope _IDL_SEQUENCE_ISOString  SOMLINK ODPartHandlerRegistryGetPartHandlerList(ODPartHandlerRegistry *somSelf, Environment *ev, ISOString partKindName, string category)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetPartHandlerList");

    /* Return statement to be customized: */
    { _IDL_SEQUENCE_ISOString retVal;  return (retVal); }
}

SOM_Scope _IDL_SEQUENCE_ISOString  SOMLINK ODPartHandlerRegistryGetPartKindList(ODPartHandlerRegistry *somSelf,
                                                                              Environment *ev,
                                                                             ISOString partHandlerName,
                                                                             string category)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetPartKindList");

    /* Return statement to be customized: */
    { _IDL_SEQUENCE_ISOString retVal;  return (retVal); }
}

SOM_Scope _IDL_SEQUENCE_string  SOMLINK ODPartHandlerRegistryGetCategoryList(ODPartHandlerRegistry *somSelf,
                                                                              Environment *ev,
                                                                             ISOString partHandlerName,
                                                                             ISOString partKindName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetCategoryList");

    /* Return statement to be customized: */
    { _IDL_SEQUENCE_string retVal;  return (retVal); }
}

SOM_Scope ODPartHandlerInfo*  SOMLINK ODPartHandlerRegistryGetPartHandlerInfo(ODPartHandlerRegistry *somSelf,
                                                                               Environment *ev,
                                                                              ISOString partHandlerName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetPartHandlerInfo");

    /* Return statement to be customized: */
    { ODPartHandlerInfo* retVal;  return (retVal); }
}

SOM_Scope ODPartHandlerInfo*  SOMLINK ODPartHandlerRegistryGetPreferredPartHandlerInfo(ODPartHandlerRegistry *somSelf,
                                                                                         Environment *ev,
                                                                                        ISOString partKindName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetPreferredPartHandlerInfo");

    /* Return statement to be customized: */
    { ODPartHandlerInfo* retVal;  return (retVal); }
}


SOM_Scope ISOString  SOMLINK ODPartHandlerRegistryGetPreferredPartHandler(ODPartHandlerRegistry *somSelf,
                                                                           Environment *ev,
                                                                          ISOString partKindName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetPreferredPartHandler");

    /* Return statement to be customized: */
    { ISOString retVal;  return (retVal); }
}

SOM_Scope long  SOMLINK ODPartHandlerRegistrySetPreferredPartHandler(ODPartHandlerRegistry *somSelf,
                                                                      Environment *ev,
                                                                     ISOString partKindName,
                                                                     ISOString partHandlerName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistrySetPreferredPartHandler");

    /* Return statement to be customized: */
    { long retVal;  return (retVal); }
}

SOM_Scope void  SOMLINK ODPartHandlerRegistryUpdateODPartHandlerInfo(ODPartHandlerRegistry *somSelf, Environment *ev, ISOString partHandlerName, _IDL_SEQUENCE_PartKindInfo * newKindInfo )
{

    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf);*/
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryUpdateODPartHandlerInfo");
}

SOM_Scope ISOString  SOMLINK ODPartHandlerRegistryGetPreferredPartHandlerForFileType(ODPartHandlerRegistry *somSelf,
                                                                           Environment *ev,
                                                                          ISOString partFileTypeName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetPreferredPartHandlerForFileType");

    /* Return statement to be customized: */
    { ISOString retVal;  return (retVal); }
}

SOM_Scope long  SOMLINK ODPartHandlerRegistrySetPreferredPartHandlerForFileType(ODPartHandlerRegistry *somSelf,
                                                                      Environment *ev,
                                                                     ISOString partFileTypeName,
                                                                     ISOString partHandlerName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistrySetPreferredPartHandlerForFileType");

    /* Return statement to be customized: */
    { long retVal;  return (retVal); }
}

SOM_Scope ISOString  SOMLINK ODPartHandlerRegistryGetPreferredPartHandlerForFileExt(ODPartHandlerRegistry *somSelf,
                                                                           Environment *ev,
                                                                          ISOString partFileExtensionName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetPreferredPartHandlerForFileExt");

    /* Return statement to be customized: */
    { ISOString retVal;  return (retVal); }
}

SOM_Scope long  SOMLINK ODPartHandlerRegistrySetPreferredPartHandlerForFileExt(ODPartHandlerRegistry *somSelf,
                                                                      Environment *ev,
                                                                     ISOString partFileExtensionName,
                                                                     ISOString partHandlerName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistrySetPreferredPartHandlerForFileType");

    /* Return statement to be customized: */
    { long retVal;  return (retVal); }
}

SOM_Scope _IDL_SEQUENCE_string  SOMLINK ODPartHandlerRegistryGetFileTypeList(ODPartHandlerRegistry *somSelf,
                                                                              Environment *ev,
                                                                             ISOString partHandlerName,
                                                                             ISOString partKindName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetFileTypeList");

    /* Return statement to be customized: */
    { _IDL_SEQUENCE_string retVal;  return (retVal); }
}

SOM_Scope _IDL_SEQUENCE_string  SOMLINK ODPartHandlerRegistryGetFileExtensionList(ODPartHandlerRegistry *somSelf,
                                                                              Environment *ev,
                                                                             ISOString partHandlerName,
                                                                             ISOString partKindName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetFileExtensionList");

    /* Return statement to be customized: */
    { _IDL_SEQUENCE_string retVal;  return (retVal); }
}

SOM_Scope _IDL_SEQUENCE_string  SOMLINK ODPartHandlerRegistryCategoryList(ODPartHandlerRegistry *somSelf,
                                                                             Environment *ev,
                                                                             ISOString partHandlerName,
                                                                             ISOString partKindName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetCategoryList");

    /* Return statement to be customized: */
    { _IDL_SEQUENCE_string retVal;  return (retVal); }
}

SOM_Scope _IDL_SEQUENCE_ISOString  SOMLINK ODPartHandlerRegistryGetPartHandlerListForFileTypes(ODPartHandlerRegistry *somSelf,
                                                                                 Environment *ev,
                                                                                 string fileType)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetPartHandlerListForFileTypes");

    /* Return statement to be customized: */
    { _IDL_SEQUENCE_ISOString retVal;  return (retVal); }
}

SOM_Scope _IDL_SEQUENCE_ISOString  SOMLINK ODPartHandlerRegistryGetPartHandlerListForFileExt(ODPartHandlerRegistry *somSelf,
                                                                                 Environment *ev,
                                                                                 string fileExtension)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetPartHandlerListForFileExt");

    /* Return statement to be customized: */
    { _IDL_SEQUENCE_ISOString retVal;  return (retVal); }
}

SOM_Scope ISOString  SOMLINK ODPartHandlerRegistryGetPreferredPartHandlerForCategory(ODPartHandlerRegistry *somSelf,
                                                                           Environment *ev,
                                                                          ISOString category)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistryGetPreferredPartHandlerForCategory");

    /* Return statement to be customized: */
    { ISOString retVal;  return (retVal); }
}

SOM_Scope long  SOMLINK ODPartHandlerRegistrySetPreferredPartHandlerForCategory(ODPartHandlerRegistry *somSelf,
                                                                      Environment *ev,
                                                                     ISOString category,
                                                                     ISOString partHandlerName)
{
    /* ODPartHandlerRegistryData *somThis = ODPartHandlerRegistryGetData(somSelf); */
    ODPartHandlerRegistryMethodDebug("ODPartHandlerRegistry","ODPartHandlerRegistrySetPreferredPartHandlerForCategory");

    /* Return statement to be customized: */
    { long retVal;  return (retVal); }
}
