/* @(#)Z 1.4 com/src/storage/idl/SURefItr.idl, odstorage, od96os2, odos29646d 96/11/15 15:27:58 (96/10/29 09:33:07) */
//#====START_GENERATED_PROLOG======================================
//#
//#
//#   COMPONENT_NAME: odstorage
//#
//#   CLASSES: none
//#
//#   ORIGINS: 82,27
//#
//#
//#   (C) COPYRIGHT International Business Machines Corp. 1995,1996
//#   All Rights Reserved
//#   Licensed Materials - Property of IBM
//#   US Government Users Restricted Rights - Use, duplication or
//#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//#   	
//#   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
//#   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//#   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
//#   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
//#   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
//#   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
//#   OR PERFORMANCE OF THIS SOFTWARE.
//#
//#====END_GENERATED_PROLOG========================================
//#

#ifdef __PRIVATE__
//#	File:		SURefItr.idl
//#
//#	Contains:	Definition of ODStorageUnitRefIterator.
//#
//#	Owned by:	Vincent Lo
//#
//#	Copyright:	(r) 1993 - 1995 by Apple Computer, Inc., all rights reserved.
//#
//#	Change History (most recent first):
//#
//#		 <6>	 8/16/95	VL		1275241: Cleaned up IDL file.
//#		 <5>	  8/3/95	RR		#1257260: Collapse B classes. Remove
//#									somInit methods. Don't call IsInitialized
//#									or SubclassResponsibility
//#		 <4>	 5/17/95	VL		1249181: Made Init method private.
//#		 <3>	 1/26/95	VL		#???: SURef is now a 4-byte array.
//#		 <2>	 6/21/94	VL		Added functionprefix.
//#		 <1>	  6/8/94	VL		first checked in
//#
//#	To Do:
//#
#else
//#	Copyright:	(r) 1993-1995 by Apple Computer, Inc., all rights reserved.
#endif

#ifndef _SUREFITR_
#define _SUREFITR_

#ifndef _ODOBJECT_
#include "ODObject.idl"
#endif

//==============================================================================
// Classes defined in this interface
//==============================================================================
interface   ODStorageUnitRefIterator;

//==============================================================================
// Classes used by this interface
//==============================================================================
interface	ODStorageUnit;

//==============================================================================
// ODStorageUnitRefIterator
//==============================================================================

interface ODStorageUnitRefIterator : ODObject
{
#ifdef __PRIVATE__
    void InitStorageUnitRefIterator(in ODStorageUnit storageUnit);
#endif

    void  First(out ODStorageUnitRef ref);
    
    void 	Next(out ODStorageUnitRef ref);
  
    ODBoolean      IsNotComplete();
  
#ifdef __SOMIDL__
	implementation
	{
		majorversion = 1; minorversion = 0;
	  	functionprefix = ODStorageUnitRefIterator;
		override:
			somUninit;
		releaseorder:
	#ifdef __PRIVATE__
			InitStorageUnitRefIterator,
	#else
			reserved1,
	#endif
			First,
			Next,
			IsNotComplete;    
	};
#endif
};

#endif  // _SUREFITR_
