/* @(#)Z 1.4 com/src/bento/localidl/CMSURefI.idl, odstorage, od96os2, odos29646d 96/11/15 15:27:47 (96/10/29 09:14:36) */
//#====START_GENERATED_PROLOG======================================
//#
//#
//#   COMPONENT_NAME: odstorage
//#
//#   CLASSES: none
//#
//#   ORIGINS: 82,27
//#
//#
//#   (C) COPYRIGHT International Business Machines Corp. 1995,1996
//#   All Rights Reserved
//#   Licensed Materials - Property of IBM
//#   US Government Users Restricted Rights - Use, duplication or
//#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//#   	
//#   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
//#   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//#   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
//#   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
//#   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
//#   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
//#   OR PERFORMANCE OF THIS SOFTWARE.
//#
//#====END_GENERATED_PROLOG========================================
//#

#ifdef __PRIVATE__
//#
//#	File:		CMSURefI.idl
//#
//#	Contains:	Definition of CMStorageUnitRefIterator
//#
//#	Owned by:	Vincent Lo
//#
//#	Copyright:	(r) 1994 by Apple Computer, Inc., all rights reserved.
//#
//#	Change History (most recent first):
//#
//#		 <4>	 8/16/95	VL		1275241: Cleaned up IDL file.
//#		 <3>	  8/3/95	RR		#1257260: Collapse B classes. Remove
//#									somInit methods. Don't call IsInitialized
//#									or SubclassResponsibility
//#		 <2>	 6/22/94	VL		Added functionprefix.
//#		 <1>	  6/8/94	VL		first checked in
//#
//#	To Do:
//#
#else
//#	Copyright:	(r) 1993 - 1995 by Apple Computer, Inc., all rights reserved.
#endif

#ifndef _CMSUREFI_
#define _CMSUREFI_

#ifndef _SUREFITR_
#include "SURefItr.idl"
#endif

//==============================================================================
// Classes defined in this interface
//==============================================================================
interface  CMStorageUnitRefIterator ;

#ifdef __PRIVATE__

//=====================================================================================
// Implementation Types
//=====================================================================================

typedef somToken CMReference;
typedef somToken CMValue;
#endif

//==============================================================================
// ODStorageUnitRefIterator
//==============================================================================

interface CMStorageUnitRefIterator : ODStorageUnitRefIterator
{

#ifdef __SOMIDL__
	implementation
	{
		majorversion = 1; minorversion = 0;
 	 	functionprefix = CMStorageUnitRefIterator;
		
		override:
		#ifdef __PRIVATE__
			InitStorageUnitRefIterator,
		#else
			reserved1,
		#endif
			somUninit,
			First,
			Next,
			IsNotComplete;
		#ifdef __PRIVATE__
			passthru C_xih = 
				""
				"#include <CMAPI.h>"
				"";
			ODBoolean			fNotComplete;
			CMReference			fReference;
			CMValue				fValue;
		#endif
	};
#endif
};

#endif  // _CMSUREFI_
