/* @(#)Z 1.5 com/src/ui/idl/DispMod.idl, odui, od96os2, odos29646d 96/11/15 15:28:34 (96/07/15 18:28:20) */
//#====START_GENERATED_PROLOG======================================
//#
//#
//#   COMPONENT_NAME: odui
//#
//#   CLASSES: none
//#
//#   ORIGINS: 82,27
//#
//#
//#   (C) COPYRIGHT International Business Machines Corp. 1995,1996
//#   All Rights Reserved
//#   Licensed Materials - Property of IBM
//#   US Government Users Restricted Rights - Use, duplication or
//#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//#   	
//#   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
//#   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//#   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
//#   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
//#   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
//#   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
//#   OR PERFORMANCE OF THIS SOFTWARE.
//#
//#====END_GENERATED_PROLOG========================================
//#
/********************************************************************/
/*  Licensed Materials - Property of IBM                            */
/*                                                                  */
/*                                                                  */
/* Copyright (C) International Business Machines Corp., 1994.       */
/* Copyright (C) Apple Computer, Inc., 1994                         */
/*                                                                  */
/*  US Government Users Restricted Rights -                         */
/*  Use, duplication, or disclosure restricted                      */
/*  by GSA ADP Schedule Contract with IBM Corp.                     */
/*                                                                  */
/*                                                                  */
/********************************************************************/
#ifdef __PRIVATE__
// IBM Change History (most recent first):                         */
//  120349  5/15/95 map  Fix problem with //# comment on #endifs   */
//  120349  5/15/95 map  Fix up IDL copyright                      */
//******************************************************************/
//
//	File:		DispMod.idl
//
//	Contains:	Class definition for ODDispatchModule
//
//	Owned by:	Richard Rodseth
//
//	Copyright:	(C) 1993 - 1995 by Apple Computer, Inc., all rights reserved.
//
//	Change History (most recent first):
//
//		 <6>	 8/15/95	RR		#1275241 IDL Review
//		 <5>	  8/3/95	RR		#1257260: Collapse B classes. Remove
//									somInit methods. Don't call IsInitialized
//									or SubclassResponsibility
//		 <4>	 6/15/95	RR		#1254828/1255536 Added eventInfo to
//									DIspatch
//		 <3>	 9/13/94	RR		#1183564 ODEventData should be inout
//		 <2>	 6/16/94	RR		Added function prefix
//		 <1>	  6/8/94	RR		first checked in
//		 <5>	  6/7/94	RR		Privatise change log
//		 <1>	  5/9/94	VL		first checked in
//
//	To Do:
//
#else
//	Copyright:	(C) 1993 - 1995 by Apple Computer, Inc., all rights reserved.
#endif

#ifndef _DISPMOD_
#define _DISPMOD_

#ifndef _ODOBJECT_
#include "ODObject.idl"
#endif

//=====================================================================================
// Classes defined in this interface
//=====================================================================================

interface  ODDispatchModule;

//=====================================================================================
// Classes used by this interface
//=====================================================================================

interface  ODSession;

//=====================================================================================
// ODDispatchModule
//=====================================================================================

interface ODDispatchModule : ODObject
{
	void InitDispatchModule(in ODSession session);

   	ODBoolean Dispatch(inout ODEventData event, inout ODEventInfo eventInfo);

#ifdef __SOMIDL__
	implementation
	{
		majorversion = 1; minorversion = 0;

	  	functionprefix = ODDispatchModule;

		releaseorder:
			InitDispatchModule,
			Dispatch;
	
	#ifdef __PRIVATE__

	#endif // __PRIVATE__

	};
#endif // __SOMIDL__
};

#endif // _DISPMOD_

