/* @(#)Z 1.2 com/src/ui/idl/FocusMod.idl, odui, od96os2, odos29646d 96/11/15 15:28:36 (96/07/15 18:28:37) */
//#====START_GENERATED_PROLOG======================================
//#
//#
//#   COMPONENT_NAME: odui
//#
//#   CLASSES: none
//#
//#   ORIGINS: 82,27
//#
//#
//#   (C) COPYRIGHT International Business Machines Corp. 1995,1996
//#   All Rights Reserved
//#   Licensed Materials - Property of IBM
//#   US Government Users Restricted Rights - Use, duplication or
//#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//#   	
//#   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
//#   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//#   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
//#   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
//#   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
//#   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
//#   OR PERFORMANCE OF THIS SOFTWARE.
//#
//#====END_GENERATED_PROLOG========================================
//#
#ifdef __PRIVATE__
//#
//#	File:		FocusMod.idl
//#
//#	Contains:	Class definition for ODFocusModule
//#
//#	Owned by:	Richard Rodseth
//#
//#	Copyright:	(r) 1993 - 1995 by Apple Computer, Inc., all rights reserved.
//#
//#	Change History (most recent first):
//#
//#		 <8>	 8/15/95	RR		#1275241 IDL Review
//#		 <7>	  8/3/95	RR		#1257260: Collapse B classes. Remove
//#									somInit methods. Don't call IsInitialized
//#									or SubclassResponsibility
//#		 <6>	 5/25/95	VL		1251403: Multithreading naming support.
//#		 <5>	  9/2/94	RR		#1184275 Pass transferringFrame and
//#									newOwner to focusModule::TransferFocus
//#		 <4>	 8/15/94	JBS		1181174: added TranferFocusOwnership()
//#		 <3>	 9/26/94	RR		Added fInitialized
//#		 <2>	 6/16/94	RR		Added function prefix
//#		 <1>	  6/8/94	RR		first checked in
//#		 <3>	  6/7/94	RR		Privatise change log
//#
//#	To Do:
//#
#else
//#	Copyright:	(r) 1993 - 1995 by Apple Computer, Inc., all rights reserved.
#endif

#ifndef _FOCUSMOD_
#define _FOCUSMOD_

#ifndef _ODOBJECT_
#include "ODObject.idl"
#endif

//=====================================================================================
// Classes defined in this interface
//=====================================================================================

interface  ODFocusModule;

//=====================================================================================
// Classes used by this interface
//=====================================================================================

interface  ODSession;
interface  ODFrame;
interface  ODFocusOwnerIterator;

//=====================================================================================
// Class ODFocusModule
//=====================================================================================

interface ODFocusModule : ODObject
{
	void InitFocusModule(in ODSession session);

	ODBoolean IsFocusExclusive(in ODTypeToken focus);

	void SetFocusOwnership(in ODTypeToken focus, in ODFrame frame);

	void UnsetFocusOwnership(in ODTypeToken focus, in ODFrame frame);

	void TransferFocusOwnership(in ODTypeToken focus, 
								in ODFrame transferringFrame,
					  			in ODFrame newOwner);

	ODFrame AcquireFocusOwner(in ODTypeToken focus);

	ODFocusOwnerIterator CreateOwnerIterator(in ODTypeToken focus);

	ODBoolean BeginRelinquishFocus(in ODTypeToken focus,
								   in ODFrame requestingFrame);

	void CommitRelinquishFocus(in ODTypeToken focus,
							   in ODFrame requestingFrame);

	void AbortRelinquishFocus(in ODTypeToken focus,
							  in ODFrame requestingFrame);

#ifdef __SOMIDL__
	implementation
  	{
		majorversion = 1; minorversion = 0;
		
  		functionprefix = ODFocusModule;
			 
		releaseorder:
			InitFocusModule,
			IsFocusExclusive,
			SetFocusOwnership,
			UnsetFocusOwnership,
			TransferFocusOwnership,
			AcquireFocusOwner,
			CreateOwnerIterator,
			BeginRelinquishFocus,
			CommitRelinquishFocus,
			AbortRelinquishFocus;
		
  	};
#endif //# __SOMIDL__
};

#endif //# _FOCUSMOD_
