//#====START_GENERATED_PROLOG======================================
//#
//#
//#   COMPONENT_NAME: odui
//#
//#   CLASSES: none
//#
//#   ORIGINS: 82,27
//#
//#
//#   (C) COPYRIGHT International Business Machines Corp. 1995,1996
//#   All Rights Reserved
//#   Licensed Materials - Property of IBM
//#   US Government Users Restricted Rights - Use, duplication or
//#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//#   	
//#   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
//#   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//#   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
//#   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
//#   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
//#   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
//#   OR PERFORMANCE OF THIS SOFTWARE.
//#
//#====END_GENERATED_PROLOG========================================
//#
/* @(#) 1.4 com/src/ui/idl/ODTemps.idl, odui, od96os2, odos29646d 10/31/96 12:46:01 [11/15/96 15:29:40] */
/********************************************************************/
/*                                                                  */
/* Copyright (C) Apple Computer, Inc., 1994                         */
/*                                                                  */
/*                                                                  */
/********************************************************************/
#ifdef __PRIVATE__
//#
//#  File:    ODTemps.idl
//#
//#  Contains:  Class definition for ODTemplates
//#
//#  Written by:  Phil Estes
//#
//#  Copyright:  (c) 1994 by IBM Corp., all rights reserved.
//#
//#  Change History (most recent first):
//#
//#  143601    11/13/95  pfe   changed RemoveTemplate to DeleteTemplate
//#  119899    05/31/95  pfe   added parameter for Object Title to CreateTemplate
//#  123249    05/31/95  pfe   changed char* to string (DSOM)
//#     <1>    ??/??/94  PFE   first checked in
//#
//#  To Do:
//#
#else
//#  Copyright:  (c) 1993-1994 by IBM Corp., all rights reserved.
#endif

#ifndef _ODTEMPS_
#define _ODTEMPS_

#ifndef _PART_
   #include "Part.idl"
#endif

//=====================================================================================
// Classes defined in this interface
//=====================================================================================

interface  ODTemplates;

//=====================================================================================
// Classes used by this interface
//=====================================================================================

interface  ODPart;
interface  ODObject;
interface  ODSession;
interface  ODStorageUnit;

#ifdef __PRIVATE__
//=====================================================================================
// Implementation Types
//=====================================================================================
//interface ODxOrderedCollection;
typedef unsigned long HOBJECT;
#endif // __PRIVATE__

//=====================================================================================
// Class ODTemplates
//=====================================================================================

#ifdef _PLATFORM_OS2_

interface ODTemplates  :  ODObject
{
      ODBoolean CreateTemplate(in ODPart part, in ODSession session,
                               in string ObjectID, in string ObjectTitle, in ODStorageUnit unit);
                                        //123249 [pfe] , 119899 [pfe]
      ODBoolean DeleteTemplate(in string ObjectID);

      ODStorageUnit GetStorageUnit(in ODSession session);
#ifdef __PRIVATE__
      ODBoolean WriteSUToTemplate(in ODSession session);
#endif
#ifdef __SOMIDL__
  implementation
  {
     functionprefix = ODTemplates;

     override:
         somInit,
         somUninit;

     releaseorder:
         CreateTemplate,
         DeleteTemplate,
#ifndef __PRIVATE__
         reserved01,
#else
         WriteSUToTemplate,
#endif
         GetStorageUnit;

     majorversion = 1; minorversion = 0;

     #ifdef __PRIVATE__

        char *fODTempLocation;
        HOBJECT fHObject;
        char *fObjID;
     #endif

  };
#endif // __SOMIDL__

};

#endif //  _PLATFORM_OS2_

#endif // _ODTEMPS_
