/* @(#)Z 1.3 os2/src/storage/idl/IODDefs.idl, oddataxfer, od96os2, odos29646d 96/11/15 15:29:37 (96/08/23 01:43:40) */
//#====START_GENERATED_PROLOG======================================
//#
//#
//#   COMPONENT_NAME: oddataxfer
//#
//#   CLASSES: none
//#
//#   ORIGINS: 82,27
//#
//#
//#   (C) COPYRIGHT International Business Machines Corp. 1995,1996
//#   All Rights Reserved
//#   Licensed Materials - Property of IBM
//#   US Government Users Restricted Rights - Use, duplication or
//#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//#   	
//#   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
//#   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//#   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
//#   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
//#   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
//#   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
//#   OR PERFORMANCE OF THIS SOFTWARE.
//#
//#====END_GENERATED_PROLOG========================================
//#

/********************************************************************/
/*                                                                  */
/* Copyright (C) Apple Computer, Inc., 1994                         */
/*                                                                  */
/********************************************************************/

#ifndef _IODDEFS_
#define _IODDEFS_

#ifndef _ODTYPESB_
  #include <odtypesb.idl>
#endif

#if defined(__SOMIDL__) && defined(EMIT_GLOBAL_IODTYPES)
#pragma somemittypes on
#endif

//#============================================================================
//# Typedefs
//#============================================================================

typedef ODISOStr IODFileName;
typedef ODULong  ODLinkConnectionID;
typedef ODISOStr IODDSOMExternalizedID;

/*
 * AuxiliaryState is the state that gets communicated between
 * a LinkSource and a LinkSourceSurrogate.  When a LinkSource calls
 * LinkSourceToAS::LinkClosed, it passes a pointer to this struct.  If
 *
 */
struct IODAuxiliaryState {
  ODULong         version;         // version of this auxilary state
  ODLinkConnectionID idCounter;       // Current value of counter.
  ODByteArray     remoteLinkInfos; // This encodes the info of registered/tracked
                                   // link targets.
};

/*
 * IODDocument is a document id assigned by the Availability Server
 * and used for linking.
*/
typedef ODULong IODDocumentID;

#if defined(__SOMIDL__) && defined(EMIT_GLOBAL_IODTYPES)
#pragma somemittypes off
#endif

module IOpenDoc_Defs
{
  const string IOpenDoc_Defs_Version = "1.0.";
};

#endif
